#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_even_fibonacci(end_value):

    n1 = 1
    n2 = 1
    even_fibonacci = []

    while True:
        
        n3 = n1 + n2
        n1 = n2
        n2 = n3

        if n3 >= end_value:
            break
        
        if n3 % 2 == 0:
            even_fibonacci.append(n3)

    return sum(even_fibonacci)

print(sum_even_fibonacci(4000000))
